### ISSUE TITLE
方便提供预训练模型吗

### ISSUE THREAD

**Issue by hcfeng201** [wqt2019/tacotron-2_melgan#2]
你好，
    一直在找更快速的声码器，所以想试试效果，方便提供预训练模型吗？

**Comment by wqt2019** [comment]
链接: https://pan.baidu.com/s/15CQwbxiiZ9VKpDnyTYP0Mg 提取码: cf5t

**Comment by hcfeng201** [comment]
感谢分享！

**Comment by zhilangtaosha** [comment]
> 链接: https://pan.baidu.com/s/15CQwbxiiZ9VKpDnyTYP0Mg 提取码: cf5t
@wqt2019 
为什么出来的声音是男声 ？
