### ISSUE TITLE
在frozen_tacotron2.py中，用inference_pb会报错

### ISSUE THREAD

**Issue by hcfeng201** [wqt2019/tacotron-2_melgan#3]
![image](https://user-images.githubusercontent.com/34930362/83217579-abf3ae80-a19e-11ea-9907-3a175ca42afe.png)
请问是跟我用的tensorflow以及python版本有关吗？

**Comment by wqt2019** [comment]
# set False when freeze model
tf_pyfunc = True	# True False
in tacotron.py

**Comment by hcfeng201** [comment]
> # set False when freeze model
> tf_pyfunc = True # True False
> in tacotron.py

非常感谢！
