### ISSUE TITLE
where is  biaobei_transcript_phone.txt  that is used in preprocess.py 

### ISSUE THREAD

**Issue by c1a1o1** [wqt2019/tacotron-2_melgan#8]
where is  biaobei_transcript_phone.txt  that is used in preprocess.py

**Comment by wqt2019** [comment]
可以直接用拼音的标签训练，也可以用音素标签训练，用音素的话，用dict.txt将拼音映射过去就可以了

**Comment by c1a1o1** [comment]
收到多谢
